@php
    $snap = is_array($submission->snapshot) ? $submission->snapshot : [];
    $vendor = $submission->vendor;
    $job = $submission->jobPosting;
    $buyer = $submission->buyer;
    $rows = $snap['rows'] ?? [];
    $totals = $snap['totals'] ?? [];
    $serviceLabel = $snap['service_label'] ?? ($job?->category ?? 'Security services');
    $location = $snap['location'] ?? ($job?->location ?? '');
@endphp
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; color:#222; font-size:12px; }
    h1 { font-size:20px; margin:0 0 4px; }
    h2 { font-size:14px; margin:18px 0 6px; border-bottom:1px solid #ddd; padding-bottom:4px; }
    .muted { color:#666; }
    table { width:100%; border-collapse:collapse; margin-top:6px; }
    th, td { padding:6px 8px; border-bottom:1px solid #eee; text-align:left; vertical-align:top; }
    th { background:#f6f8fb; font-size:11px; text-transform:uppercase; }
    .right { text-align:right; }
    .totals td { font-weight:bold; border-top:2px solid #444; border-bottom:none; }
    .header-band { background:#0d6efd; color:#fff; padding:14px 18px; }
    .meta { width:100%; margin-top:10px; }
    .meta td { border:none; padding:3px 8px; }
</style>
</head>
<body>
    <div class="header-band">
        <h1 style="color:#fff;">Vendor Estimate</h1>
        <div class="muted" style="color:#cfe1ff;">{{ $serviceLabel }}@if($location) · {{ $location }}@endif</div>
    </div>

    <table class="meta">
        <tr>
            <td><strong>From:</strong> {{ $vendor?->name }}@if($vendor?->company) — {{ $vendor->company }}@endif</td>
            <td><strong>To:</strong> {{ $buyer?->name }}@if($buyer?->company) — {{ $buyer->company }}@endif</td>
        </tr>
        <tr>
            <td><strong>Job:</strong> {{ $job?->title ?? '—' }}</td>
            <td><strong>Submitted:</strong> {{ $submission->created_at?->format('M j, Y') }}</td>
        </tr>
    </table>

    <h2>Cost breakdown</h2>
    @if(!empty($rows))
        <table>
            <thead>
                <tr>
                    <th>Line item</th>
                    <th class="right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>
                        <td>{{ $row['label'] ?? '' }}</td>
                        <td class="right">{{ $row['value'] ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p class="muted">No line items captured.</p>
    @endif

    @if(!empty($totals))
        <h2>Totals</h2>
        <table class="totals">
            @foreach($totals as $row)
                <tr>
                    <td>{{ $row['label'] ?? '' }}</td>
                    <td class="right">{{ $row['value'] ?? '' }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    @if(!empty($snap['notes']))
        <h2>Notes</h2>
        <div>{{ $snap['notes'] }}</div>
    @endif

    <p class="muted" style="margin-top:24px;font-size:11px;">
        Generated by GASQ — getasecurityquote.com
    </p>
</body>
</html>
