-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type text NOT NULL,
  event_data jsonb,
  session_id text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bids (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  amount numeric NOT NULL,
  proposal text,
  status USER-DEFINED DEFAULT 'pending'::bid_status,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  responded_at timestamp with time zone,
  estimated_start_date date,
  message text,
  CONSTRAINT bids_pkey PRIMARY KEY (id),
  CONSTRAINT bids_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(id),
  CONSTRAINT bids_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.buyer_prequalification (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  is_decision_maker boolean,
  has_approved_budget boolean,
  needs_services_within_45_days boolean,
  has_inhouse_security_staff boolean,
  has_current_vendor_onsite boolean,
  wants_vendor_replacement_guarantee boolean,
  wants_price_lock_guarantee boolean,
  knows_inhouse_cost boolean,
  requires_livable_wage boolean,
  requires_health_benefits boolean,
  requires_insurance boolean,
  requires_working_capital_45_60_days boolean,
  qualified boolean DEFAULT ((is_decision_maker = true) AND (has_approved_budget = true)),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT buyer_prequalification_pkey PRIMARY KEY (id),
  CONSTRAINT buyer_prequalification_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.buyer_prequalification_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  prior_crimes_near_property text,
  regular_crime_analysis text,
  unsafe_reports text,
  current_security_measures ARRAY,
  previous_security_vendors text,
  written_security_policies text,
  liability_insurance text,
  mutual_hold_harmless_agreement text,
  sb68_awareness text,
  decision_maker text,
  security_budget_type text,
  decision_maker_type text,
  budget_allocated text,
  budget_range text,
  service_type text,
  coverage_hours text,
  insurance_requirement text,
  services_without_insurance text,
  decision_timeline text,
  selection_factor text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT buyer_prequalification_responses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.buyer_questionnaire_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  contact_name text,
  contact_email text,
  contact_phone text,
  company_name text,
  property_address text,
  organization_type text,
  organization_type_other text,
  security_services ARRAY,
  security_services_other text,
  desired_start_date date,
  desired_end_date date,
  hours_per_week text,
  budget_allocated text,
  budget_range text,
  require_multiple_bids text,
  require_multiple_bids_explain text,
  decision_maker_role text,
  board_authorization text,
  procurement_timeline text,
  follow_up_method text,
  current_threat_level text,
  current_vulnerability_level text,
  prior_crimes_on_property text,
  prior_crimes_details text,
  current_security_measures ARRAY,
  can_add_to_insurance text,
  mutual_hold_harmless text,
  agree_to_risk_assessment text,
  recent_risk_assessment text,
  known_crime_stats text,
  crimes_against_people text,
  crimes_against_property text,
  budget_verified text,
  know_inhouse_cost text,
  price_shopping_only text,
  working_capital_required text,
  regular_crime_analysis text,
  safety_reports text,
  previous_security_vendors text,
  previous_vendor_details text,
  written_security_policies text,
  liability_insurance text,
  aware_of_sb68 text,
  direct_warnings text,
  pattern_of_risk text,
  should_have_known text,
  crimes_within_500_yards text,
  onsite_person_crimes text,
  nearby_safety_reports text,
  property_crime_experience text,
  security_breaches text,
  public_access_points text,
  lighting_conditions text,
  current_staffing text,
  threat_perception text,
  preparedness text,
  coverage_type text,
  insurance_requirement text,
  decision_timeline text,
  important_factor text,
  cri_score integer,
  crs_score integer,
  bqs_score integer,
  bfi_score integer,
  risk_level text,
  critical_level text,
  buyer_fit text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT buyer_questionnaire_responses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  job_id uuid,
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(id)
);
CREATE TABLE public.economic_justification_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_name text,
  prepared_by text,
  prepared_for text,
  calculation_data jsonb NOT NULL,
  comments text,
  uploaded_files jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT economic_justification_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feature_usage_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  feature_key text NOT NULL UNIQUE,
  feature_name text NOT NULL,
  tokens_required integer NOT NULL CHECK (tokens_required >= 0),
  role text CHECK (role = ANY (ARRAY['buyer'::text, 'vendor'::text, 'both'::text])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feature_usage_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.file_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  filename text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  mime_type text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT file_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT file_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.free_pool (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  month text NOT NULL UNIQUE,
  total_tokens integer NOT NULL CHECK (total_tokens >= 0),
  tokens_used integer NOT NULL DEFAULT 0 CHECK (tokens_used >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT free_pool_pkey PRIMARY KEY (id)
);
CREATE TABLE public.free_pool_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  free_pool_id uuid NOT NULL,
  tokens_granted integer NOT NULL CHECK (tokens_granted > 0),
  claim_type text NOT NULL CHECK (claim_type = ANY (ARRAY['signup'::text, 'first_rfp'::text, 'first_bid'::text, 'monthly'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT free_pool_claims_pkey PRIMARY KEY (id),
  CONSTRAINT free_pool_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT free_pool_claims_free_pool_id_fkey FOREIGN KEY (free_pool_id) REFERENCES public.free_pool(id)
);
CREATE TABLE public.gasq_estimator_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_type text,
  step_1_complete boolean DEFAULT false,
  step_2_complete boolean DEFAULT false,
  step_3_complete boolean DEFAULT false,
  step_4_complete boolean DEFAULT false,
  general_questions_complete boolean DEFAULT false,
  buyer_questions_complete boolean DEFAULT false,
  vendor_questions_complete boolean DEFAULT false,
  crime_questions_complete boolean DEFAULT false,
  general_questions_data jsonb,
  buyer_questions_data jsonb,
  vendor_questions_data jsonb,
  crime_questions_data jsonb,
  calculator_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gasq_estimator_progress_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  match_score numeric,
  match_reasons jsonb,
  notified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_matches_pkey PRIMARY KEY (id),
  CONSTRAINT job_matches_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(id),
  CONSTRAINT job_matches_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.job_postings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  location text NOT NULL,
  zip_code text,
  service_start_date date,
  service_end_date date,
  coverage_days ARRAY,
  daily_start_time time without time zone,
  daily_end_time time without time zone,
  guards_per_shift integer,
  property_type text,
  special_requirements ARRAY,
  budget_min numeric,
  budget_max numeric,
  description text,
  is_private boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'draft'::job_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT job_postings_pkey PRIMARY KEY (id),
  CONSTRAINT job_postings_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  message text NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  related_id uuid,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_type USER-DEFINED NOT NULL,
  company_name text,
  contact_name text,
  phone_number text,
  phone_verified boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  city text,
  state text,
  zip_code text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  referral_code text UNIQUE,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.referral_share_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  referral_code text NOT NULL,
  sharing_method text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_share_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tier_level integer NOT NULL UNIQUE,
  name text NOT NULL,
  referrals_required integer NOT NULL CHECK (referrals_required >= 0),
  bonus_credits integer NOT NULL CHECK (bonus_credits >= 0),
  badge_icon text NOT NULL,
  badge_color text NOT NULL,
  perks jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_tiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_user_id uuid NOT NULL,
  referred_user_id uuid NOT NULL UNIQUE,
  referral_code text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text])),
  completed_at timestamp with time zone,
  first_action_type text CHECK (first_action_type = ANY (ARRAY['job_post'::text, 'bid'::text])),
  credits_awarded integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sharing_method text,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_user_id_fkey FOREIGN KEY (referrer_user_id) REFERENCES auth.users(id),
  CONSTRAINT referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reviewer_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  job_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(id)
);
CREATE TABLE public.saved_achievement_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  message text NOT NULL,
  title text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_favorite boolean NOT NULL DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  CONSTRAINT saved_achievement_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  billing_interval text NOT NULL CHECK (billing_interval = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  features jsonb DEFAULT '[]'::jsonb,
  max_users integer DEFAULT 1,
  max_projects integer DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stripe_price_id text,
  stripe_product_id text,
  one_time_price_multiplier numeric DEFAULT 0.01,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.token_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  token_amount integer NOT NULL CHECK (token_amount > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  is_premium boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  stripe_price_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT token_packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tokens_change integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['purchase'::text, 'spend'::text, 'grant'::text, 'refund'::text])),
  reference_type text CHECK (reference_type = ANY (ARRAY['estimate'::text, 'job_post'::text, 'bid'::text, 'admin'::text, 'unlock_contact'::text, 'appraisal_pdf'::text, 'package_purchase'::text])),
  reference_id uuid,
  description text,
  balance_after integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'trial'::text])),
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  ends_at timestamp with time zone,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stripe_subscription_id text,
  stripe_customer_id text,
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_tier_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tier_id uuid NOT NULL,
  achieved_at timestamp with time zone DEFAULT now(),
  bonus_awarded boolean DEFAULT false,
  CONSTRAINT user_tier_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_tier_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_tier_achievements_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.referral_tiers(id)
);
CREATE TABLE public.vendor_capabilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  legal_business_name text,
  dba_name text,
  business_structure text,
  business_address text,
  website text,
  duns_number text,
  uei_number text,
  cage_code text,
  business_license_number text,
  states_licensed ARRAY,
  core_competencies ARRAY,
  past_performance jsonb,
  differentiators text,
  certifications ARRAY,
  naics_codes ARRAY,
  psc_codes ARRAY,
  general_liability_insurance text,
  professional_liability_insurance text,
  workers_comp_coverage text,
  bonding_capacity text,
  service_areas ARRAY,
  additional_info text,
  authorized_rep_name text,
  authorized_rep_title text,
  signature_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  license_verified boolean DEFAULT false,
  insurance_verified boolean DEFAULT false,
  background_check_verified boolean DEFAULT false,
  profile_completion_score integer DEFAULT 0,
  years_of_experience integer,
  team_size text,
  response_time text DEFAULT '24 hours'::text,
  availability_schedule jsonb,
  CONSTRAINT vendor_capabilities_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_capabilities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_capabilities_access_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  accessed_by_user_id uuid NOT NULL,
  vendor_profile_id uuid NOT NULL,
  access_type text NOT NULL,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_capabilities_access_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vendor_ratings_summary (
  vendor_id uuid NOT NULL,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0.00,
  total_jobs_completed integer DEFAULT 0,
  response_rate numeric DEFAULT 0.00,
  on_time_completion_rate numeric DEFAULT 0.00,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_ratings_summary_pkey PRIMARY KEY (vendor_id),
  CONSTRAINT vendor_ratings_summary_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  verification_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  document_url text,
  verified_by uuid,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_verifications_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id),
  CONSTRAINT vendor_verifications_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.verification_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  ip_address inet,
  user_agent text,
  success boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_attempts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.verification_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  code text NOT NULL,
  type text NOT NULL,
  phone_number text,
  email text,
  status USER-DEFINED DEFAULT 'pending'::verification_status,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:10:00'::interval),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_codes_pkey PRIMARY KEY (id),
  CONSTRAINT verification_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance integer NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);